[project]
name = "ed-afk-monitor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "discord>=2.3.2",
    "pyinstaller>=6.12.0",
    "requests>=2.32.3",
]
